# Generated by Django 5.0.3 on 2024-03-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='education',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='favorite_books_movies_tv_shows',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='favorite_quotes',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='fitness_activities',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='music_preferences',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='pet_ownership',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='relationship_status',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='travel_experiences',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='volunteer_work',
        ),
    ]
