# Generated by Django 5.0.3 on 2024-03-12 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('customer', 'Customer'), ('client', 'Client')], max_length=20)),
                ('chat_number', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('completed', 'Completed')], default='new', max_length=20)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
